language: r

# https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages
matrix:
    include:
        - os: osx
          env: PYTHON_VERSION=3.6
        - os: osx
          env: PYTHON_VERSION=3.7
        - os: linux
          dist: xenial
          python: 3.6
          env: PYTHON_VERSION=3.6
        - os: linux
          dist: xenial
          python: 3.7
          env: PYTHON_VERSION=3.7

# Command to install dependencies
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        export TAR=/bin/tar;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        export TAR=/usr/bin/tar;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    # Install r-base and r-essentials for estimators
    - conda create -q -n test-environment python=$PYTHON_VERSION r-base r-essentials
    - source activate test-environment
    - pip install -r requirements.txt

# Command to run tests
script:
    # Linting
    - sh lint.sh
    # This takes a while since the R estimators are expensive to build
    - python -m whynot_estimators install causal_forest
    - python -m whynot_estimators install tmle
    # Unit tests
    - pytest tests

notifications:
      email: false
